#ifndef SLAM_SLAM_CHANNELS_HPP
#define SLAM_SLAM_CHANNELS_HPP

#define SLAM_MAP_CHANNEL "SLAM_MAP"
#define SLAM_POSE_CHANNEL "SLAM_POSE"
#define SLAM_PARTICLES_CHANNEL "SLAM_PARTICLES"


#define SLAM_MAP_LOCAL_CHANNEL "SLAM_MAP_LOCAL"
#define SLAM_POSE_LOCAL_CHANNEL "SLAM_POSE_LOCAL"
// #define SLAM_PARTICLES_LOCAL_CHANNEL "SLAM_PARTICLES_LOCAL"

#endif // SLAM_SLAM_CHANNELS_HPP
